name: 'Games Notify'
description: 'Notification action for games repository'
author: 'mswnlz'
inputs:
  message:
    description: 'The message to print'
    required: false
    default: 'Hello from Games Action!'
runs:
  using: 'node20'
  main: 'index.js'
